### ISSUE TITLE
Use of "scopes" name in responses is confusing

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#158]
The use of a `scopes` field is confusing in the introspection response alongside the existing `scope` parameter with different semantics and syntax.

While technically distinct, it's not a good idea to pick a name this close that's not compatible.

**Comment by xmlgrrl** [comment]
For reference:

- The scopes field being discussed is defined in Core Sec 3.3.2 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.3.2).

- The distinct concept of "scope" being referred to here is defined in RSR Sec 1.2 (https://docs.kantarainitiative.org/uma/rec-oauth-resource-reg.html#rfc.section.1.2). "This specification enhances the OAuth concept of a "scope" by defining scopes as applying to particular registered resource sets, rather than leaving the relevant resources (such as API endpoints or URIs) implicit. A resource set can have any number of scopes, which together describe the universe of actions that can be taken on this protected resource set." (Note that RSR has been defined in such a way as to be usable with not just UMA but also with OAuth and OIDC, though to my knowledge it hasn't yet been used with the latter two.)

**Comment by mmachulak** [comment]
Use of "scopes" in responses is confusing?

or

Use of "scopes" name in responses is confusing? 

Probably the latter. Renaming the issue

**Comment by mmachulak** [comment]
Agreed that this is something to be discussed. Currently we only say "scopes" and not "OAuth scopes" or "UMA scopes".

**Comment by jricher** [comment]
Note that I'm talking about the actual syntactic keyword here. The use of `scopes` as a keyword in the JSON is much too close to the existing `scope` which has different syntax and semantics. I would suggest UMA use a completely different term if it really doesn't mean OAuth scopes.

**Comment by mmachulak** [comment]
Well, definitely to be discussed with the group. Can you propose the terms you were thinking of?

**Comment by jricher** [comment]
Anything that's more distant, even `scope_set` would be preferable.

**Comment by jricher** [comment]
Note that in introspection we changed from `scope` in the response being a JSON array to a string containing space-separated values so that it would align with RFC6749.

**Comment by xmlgrrl** [comment]
In 2.0 Core rev 07 we renamed to `permission_scopes`, and then in rev 08 aligned the name with our terminology and permission request work, renaming to `resource_scopes`. The structure is deliberately based on the resource description format defined in RReg, so it's an array that takes strings. (That hasn't changed from before.)
