### ISSUE TITLE
Client unable to specify scopes

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#165]
A client speaking to an API is likely to know more about the kind of access it requires than the RS, but the RS is the entity that determines which scopes are attached to a ticket. Since the RS has absolutely no idea which client is asking or what it might want, the RS simply has to _guess_ which scopes the client, whoever they are, might possibly want.

Suggested fix: allow the client to specify scopes with the RPT request, likely as part of #153. Provide direction in the specification of how to reconcile client's requested scopes along with the ticket's scopes (what if the client asks for more scopes than what's in the ticket? what if the client asks for no scopes?)

**Comment by gffletch** [comment]
My understanding is that the RS defines what scopes are allowable for a given resource as it is authoritative for that resource. In many cases (especially with a RESTful API) the HTTP method defines some constraints around the scopes being requested. This does create an scenario where the client might have to go through multiple RPT requests as the RequestingParty requires different capabilities with the resource.

Allowing the client to give a hint as to the access it would like would allow an optimized flow such that the client and RequestingParty might only need to go through the claims negotiation flow once.

**Comment by jricher** [comment]
The RS defines scopes in two steps: once when the resource is registered, and once when the ticket is created. The ticket has (what is assumed but not stated to be) a subset of the scopes that the RS is registered with, but when the ticket is created the RS has no insight as to what the client might want. When the ticket is presented to the AS, the AS has no insight as to what the client might want.

**Comment by gffletch** [comment]
Yes, I agree that there isn't a way for the client to give a hint of what it wants. However, this doesn't stop the flow from working, it just means that the client has to go back and get a new RPT every time it tries to do something that requires a new "scope". This is chatty but will work.

**Comment by jricher** [comment]
Not really -- it only works if the RS puts *all* scopes in *every* ticket *every* time, and the client gets a subset of that. That tells me that the tickets shouldn't even have scopes on them if the RS doesn't have a real choice about what to limit. The client can't tell the RS it wants something more, and it has no chance of self-limiting its access.

**Comment by gffletch** [comment]
Hmm... lets say we have a client that wants to both read and write a resource. Also assume the resource server has registered the resource with scopes of "read", "write" and "delete". 

The client initially requests the resource URL using an HTTP GET request and the client does not have an RPT. The RS requests a ticket with a "read" scope as the inbound request is an HTTP GET. The Client then goes through the flow to get an RPT based on a ticket that was generated based on the "read" scope. When the client then tries to update the resource via the resource URL, and the RS requests introspection at the AS using the existing RPT, it will get back that the RPT only supports "read". At this point the RS requests a new ticket with the "write" permission and sends back an "unauthorized" response. The Client then goes through the claims-negotiation flow to get a new RPT which will effectively authorize it to represent both read and write scopes. When the Client retries the update action, it will now succeed because the introspection of the RPT will include both "read" and "write".

**Comment by jricher** [comment]
This works great (if horribly inefficiently) -- *if* your API follows a very specific and limited pattern such as the kind of thing mentioned in #161 and #162. An underlying issue is that UMA has an implicit set of assumptions about the structure of the APIs it protects. UMA should either try to be more relaxed or be up front about these limitations and assumptions.

**Comment by gffletch** [comment]
I agree that in its extreme this is inefficient, so allowing the client to specify a hint/request what it wants is a useful extension to the spec. I don't think it should be required and the RS is still authoritative for how it wants to handle/honor this hint.

As for the fact that UMA assumes a very REST based model, I think it's great that you are raising the implications of that assumption.

**Comment by xmlgrrl** [comment]
For reference: The mechanism of registering a requested permission is defined in Core Sec 3.2 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.2).

**Comment by jamesghazard** [comment]
I'm new around here, so please tolerate my ignorance/learning.  I presume that (i) an RS should disclose as little as necessary (including the list of what it has available) and (ii) most requests for resources will bear strong similarities to prior requests.  Because of (ii), even if there is some ping-pong for the Requesting Party Agent to figure out what it can ask and the RS to figure out what the Requesting Party Agent needs to know, the Requesting Party Agent will ordinarily be able to remember this from session to session and ordinarily the list will not have changed.  Is it possible/sensible to treat the list of available resources as itself a resource, and make it available in a granular way?  (Is this already being done, and my question is itself a request for enlightenment rather than a suggestion?)

**Comment by andihindle** [comment]
I agree that there is a potential inefficiency in the flow as @gffletch describes it, in that if your client wants to carry out multiple actions on the same resource within a small time window, the client will likely only have permission do carry out one of those actions, and will need to run a new permissioning flow to get the next permission.  

The protection that this affords is important: the resource owner could easily (and should have the ability to) change what rights the RqP should have, between one request and the next (note that the timestamps on tokens are optional, IIRC).

I'm not sure that the assumptions the spec currently makes about REST necessarily translate into an issue here, however.  I agree that most of us probably think of things like /read and /write.  But actually, your scopes, and the behaviour of your application, can be whatever you like.  So you could perfectly well have scopes like 'read+write', for example....  Or '/update-all' or '/restart-the-server' as an amalgamation of '/stop' and '/start' or whatever.

I think...

**Comment by jricher** [comment]
@jamesghazard: for (i) the RS needs to at least know the kind of API that it is -- the scopes that it has available -- in order to afford limited protections. It doesn't need to divulge the actual information that it has in order to do this. For (ii) this may possibly be true for the same client, but an RS is going to be accessed by many clients. These clients may have different capabilities or desires, and the RS cannot possibly predict what a client might want ahead of time, which is what's currently required of it.

**Comment by jamesghazard** [comment]
Thanks.  On (i) does that mean that it discloses the types of information that it has (that it has - or might have - info on a subject)? On (ii), wouldn't the various clients have an incentive to remember what they can get from an RS - and thereby avoid the ping-pong of being re-informed?

**Comment by xmlgrrl** [comment]
This issue has an interaction with #152 as well. If the RS is allowed to ask for multiple permissions (that is, multiple resource sets, each with multiple scopes on it), what does it mean for the client to ask for scopes from the AS -- that is, for which resource set? The easiest answer may be "the scopes for the resource that the client attempted access to", and anything else it gets is gravy.

**Comment by xmlgrrl** [comment]
This was implemented in UMA 2.0 Core rev 02: https://docs.kantarainitiative.org/uma/ed/uma-core-2.0-02.html#uma-grant-type
