### ISSUE TITLE
RPT Endpoint example styled confusingly

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#166]
The RPT endpoint is listed in the example as `authz_request` which is confusingly similar to the existing OAuth 2.0 `authorization_endpoint` which is also in the discovery document. 

Suggested fix: abolish the RPT Endpoint a la #153 or at least rename the example to `rpt_endpoint`.

**Comment by xmlgrrl** [comment]
For reference: This is referring to Core Sec 3.4.1 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.4.1).

(The RPT endpoint was previously called the authorization request endpoint, and was renaming precisely because of this potential confusion. Changing the example endpoint name in this section was overlooked in the overall endpoint name change.)

**Comment by mmachulak** [comment]
Agreed, the example could be improved. Let's name this /rpt_endpoint as suggested.

**Comment by xmlgrrl** [comment]
Changed to /rpt_uri, which is what we've done elsewhere.
