### ISSUE TITLE
Can resources register without scopes

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#171]
The `scopes` parameter (confusingly named, see #158) is required in the resource registration request but it appears that it may be empty. Does this mean that a resource can register with no scopes?

**Comment by mefarazath** [comment]
And in the case where no scopes are registered how will the Authorization API respond to an RPT request?

**Comment by gffletch** [comment]
One of the value of the UMA scopes parameters is to allow the Resource Owner to construct different policy based on the different scopes. It is fine (in my opinion) to register a resource without any scopes, it just means the user is only able to define a single authorization policy for that resource. The ability to allow read access to my photo but not print access is gone. It's only all access to the photo which would require the RO to potentially construct an authorization policy that covers the most restrictive use case.

**Comment by xmlgrrl** [comment]
For reference: The parameter in question is defined in RSR Sec 2.2 (https://docs.kantarainitiative.org/uma/rec-oauth-resource-reg.html#rfc.section.2.2).

**Comment by xmlgrrl** [comment]
Wrt the above comment, specifically, by the time the RS registers a requested permission (so, at some point after resource registration time -- possibly just after -- and during client access attempt time), at least one scope has to have been associated with a resource set. This is because the process of registering a permission for it has to point to at least one.

https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.2
"scopes
REQUIRED. An array referencing one or more identifiers of scopes to which access is needed for this resource set. Each scope identifier MUST correspond to a scope that was registered by this resource server for the referenced resource set."

So one way to look at is is that if there were no applicable scopes at first RSR creation time, later on there may be some added in an update prior to permission registration time. (I have no idea why scopes would be *that* dynamically associated with resource sets, however.)

**Comment by xmlgrrl** [comment]
Discussion on 2015-08-13: This seems to be a V1.1 issue, likely with V1.0.1 implications for prefiguring what we'll do in the later version.

**Comment by xmlgrrl** [comment]
As discussed on UMA telecon 2015-08-27: Eve SWAG'd some text guessing that we would require at least one scope to be registered in future. But no one is crazy about making this kind of a decision now. So let's revert it. We can close this, presuming Maciej has already implemented amendments made on the call.
