### ISSUE TITLE
Use the oxford comma

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#195]
The following sentence should probably use the oxford comma for clarity:

```
If the client's request at the protected resource has no RPT, or an invalid RPT or insufficient authorization data associate...
```

Replace with:

```
If the client's request at the protected resource has no RPT, an invalid RPT, or insufficient authorization data associate...
```

Other parts of the specification should use it, also, but this is the one example that jumped out.

**Comment by jricher** [comment]
This same text occurs in §3 and §3.2

**Comment by xmlgrrl** [comment]
I do love the Oxford comma!

But actually, in these cases, the text is technically correct as written. This is because the phrase "as determined through RPT status checking" applies only to the "invalid RPT" and "insufficient authorization data associated with an RPT" options.

I think I can improve the feel of all of these sentences and take away the urge to comma-ize by adding "...or *has* an invalid RPT, or insufficient...".
