### ISSUE TITLE
Change "format derived from" to "format defined by"

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#196]
In §3.2.1, "using a format derived from the scope description format specified in [OAuth-resource-reg]," is misleading, should be "using a format specified in [OAuth-resource-reg]," as there is no derivation needed.

**Comment by xmlgrrl** [comment]
Actually, this phrase is wrong in a different way! It should say "resource set description format", not "scope description format". Jeez, I wonder how long that's been incorrect.

I do think "derived by" is correct, though, because the RSR version of the resource set description format allows for name, uri, type, and icon_uri properties, and this one doesn't, and this one requires a resource_set_id property that RSR doesn't have.
