### ISSUE TITLE
Erroneous normative term in use

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#210]
RFC 2119 does not define `STRONGLY RECOMMENDED` as a normative term, yet it is used twice in §7.4.1, once in §3.3.3, and once in §3.6.2.2. It should be either `RECOMMENDED` or `REQUIRED`, with my vote towards the latter in the trust framework cases and the former in the state case.

**Comment by xmlgrrl** [comment]
In the case of 3.6.2.2, we were inspired by the wording around OAuth's `state` parameter:

http://tools.ietf.org/html/rfc6749#section-4.1.1

Is there a good enough reason to diverge from OAuth in this respect (especially since it's backwards incompatible for this release)?

**Comment by jricher** [comment]
I'm confused by your comment: the section you linked has the normative term `RECOMMENDED` and not `STRONGLY RECOMMENDED`. If anything, UMA is already divergent from OAuth by adding a new normative term.

**Comment by xmlgrrl** [comment]
Sorry, left out some of my thinking, and I also just realized that I think I got your suggestion backwards.

Basically, RECOMMENDED (no matter how strongly, since the "s-word" isn't normative) still isn't REQUIRED. So if I were to correct to keep the text roughly the same in all cases, I could just remove "STRONGLY".

I was thinking you wanted to require `state` -- but you're saying recommending its use is aligned with OAuth. So that one's good.

Regarding the trust framework cases, since we're mostly prescribing human behavior, does a MUST help? I can also think of deployment scenarios, such as Gluu's, that might be entirely "internal" or "enterprise", and thus have no huge trust framework consequences.

(I don't feel *that* strongly about it, though.)

**Comment by jricher** [comment]
Literally the only thing I'm saying here is that `STRONGLY RECOMMENDED` isn't a normative tag. Remove `STRONGLY` to keep the current meaning and it's fine. Anything else would be a breaking change, require WG review, and not be fit for a patch release.

**Comment by jricher** [comment]
To clarify: if you meant `REQUIRED` when you said `STRONGLY RECOMMENDED` then just say `REQUIRED`. But from your explanation above, you didn't, so make it `RECOMMENDED`.

**Comment by xmlgrrl** [comment]
Ohhh. All is clear now. No, I think we just meant "we'd love to make this a REQUIRED but it's not truly testable and we want to be parsimonious with our MUSTs, so we just think it's a super-good idea".

**Comment by xmlgrrl** [comment]
In UMA ad hoc telecon 2015-09-08 (which had quorum), this was the discussion and conclusion:

"Removed the STRONGLY from RECOMMENDED — okay."

Will keep the change and close the issue.
