### ISSUE TITLE
What does "fail to act on the request" mean?

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#219]
In §2.3 of rs-reg, the text states that the AS "MUST fail to act on the request" if an unknown verb is used. What does it mean to fail to act on the request? If the request is for a DELETE on the {rsreguri}, there is no action defined for the request to either fail or succeed to act upon. 

Suggest removing this spurious normative language.

**Comment by xmlgrrl** [comment]
Good point; 405 is already an error, so we've already said what the AS should do when an unknown verb is used.

If the request is for, say, a DELETE on {rsreguri}, I think we may have a hole: a missing RSR-level error code that we need to define, akin to the Core spec's invalid_request in Core 4.2: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The authorization server MUST respond with the HTTP 400 (Bad Request) status code." ??

**Comment by jricher** [comment]
I say that specific example is just a 405 because it's a different URI. It's not a missing parameter so much as a verb used on a bad path. You happen to be using path elements as API parameters, yes, but that's beside the point. I suggest we leave it as a 405, remove the above normative language.

**Comment by xmlgrrl** [comment]
(BTW, I've removed "MUST fail to act on the request" in 4b548c3 but haven't closed any of these issues quite yet till we see if people are happy with the results.)

So you think the 405 suffices in your DELETE case and all other cases of incorrectness of API calls?

**Comment by jricher** [comment]
Probably. Errors that aren't explicitly mentioned are likely to be handled by regular HTTP control mechanisms in implementations.

**Comment by xmlgrrl** [comment]
In UMA ad hoc telecon 2015-09-08 (which had quorum), this was the discussion and conclusion:

"We should be fine in RSR with the 405 error for all unsupported methods."

We’ll keep the change and close the issue.
