### ISSUE TITLE
Resource Reg Section 2.1: "URI MUST resolve to a scope description document"

### ISSUE THREAD

**Issue by nynymike** [KantaraInitiative/wg-uma#269]
[Section 2.1](https://docs.kantarainitiative.org/uma/ed/oauth-resource-reg-2.0-03.html#resource-set-desc) 
```
If a scope is a URI, then it MUST resolve to a scope description document
```

I was contemplating the above... and wondering what you mean by "resolve." If the URI is a URN, then you just mean it must be defined somewhere?  And why can't the URI be a collision-resistant string?

**Comment by xmlgrrl** [comment]
This is a good point. And if we really mean MUST, then this is probably underspecified. What happens if it doesn't resolve?

**Comment by xmlgrrl** [comment]
From [UMA telecon 2017-03-02](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-03-02): Note that OIDC's discovery doc already has scopes_supported, which, if filled with URIs, enables static discovery of an UMA scope description document if you want it to. So a closed ecosystem of the sort James mentioned in the #269 thread could be handled this way. (And in the decision just above, we already have an I18N mechanism.)
So option 4 from the email thread is the current best option on the table: "Change even more to say that scope description metadata is possible to standardize, publicize, and reference through a URI, but there is no expectation of run-time resolution by the AS; rather any customization of policy condition setting interfaces with respect to scopes is, um, out of scope." So far, most implementations are only handling the simple strings, while one implementation is drawing the relevant text at run time. Since there's a way to do it statically but machine-readably, let's drop the MUST. Clear consensus on this.
