### ISSUE TITLE
Type property on scope description documents parallel to the one on resource description documents

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#292]
Should we add a "type" field to scope description documents, like we have for resource description documents? (See RReg rev 07 [Sec 2.1.1](https://docs.kantarainitiative.org/uma/wg/oauth-resource-reg-2.0-07.html#action-desc).) It would, for example, allow HEART's UMA+FHIR profile to let an AS unify interpretation of all the instances of the "ETH" scope where it appears on all the resources. 

There is a standardized semantic in the health world for the "ETH" sensitivity label and many others, and it appears that making these into "cross-cutting" scopes -- that is, scopes that apply to all resources -- is the right way to handle them. In fact there are quite a few sources of these sensitivity labels and other classification codes, and I'm not actually positive there aren't overlapping ones.

Especially if there's a possibility of overlapping semantics, it would be seem to be good for interoperability for RS's to be able to "type" scopes. (HEART is already profiling in a way that leverages the existing "type" field on resource description documents to point to HL7 resource types, as that field was designed to be used. I'm having trouble linking to that spec right now; will update with the problem is resolved.)

**Comment by jricher** [comment]
I don't believe this is a very useful field and we should not add it. If we did, we would need to define clear semantics what "type" would mean to various components, as well as have very clear behaviors of what to do when "type" was missing or invalid. Since scope descriptions are optional to understand now, adding information to them that the AS now has to consider is problematic to me. 

Comparing this proposed "type" field to the "type" field in a resource set is a false equivalence since the resource set information is pushed to the AS and is part of a required data model for all resource sets. This would be an optional addition to only some scopes (that fit a particular format AND can be dereferenced by the AS AND are properly described AND have semantics that the AS understands, etc...). 

Additionally, given that the HEART use cases are listed as motivations above, I don't believe that HEART needs this functionality either. The ETH scope [as currently proposed](http://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?modeAsFormat=html/ascii&url=https://bitbucket.org/openid/heart/raw/master/openid-heart-fhir-oauth2.xml#rfc.section.3) would be naturally used across multiple resources, just as the "read" and "write" scopes do, but controlling information on a different dimension. Trying to map these into "types" is to start down a path of creating ontologies for access control, and I don't believe that to be a fruitful or enjoyable exercise for anyone.

Let scopes stay strings, and for most use cases they'll be usable with string comparison and nothing else.

**Comment by xmlgrrl** [comment]
Per [UMA telecon 2017-03-23](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-03-23): Eve was concerned about potential scope collisions. But George points out that collisions would be bad in the context of a whole set of resources that a client would be dealing with, and Justin notes that in UMA, scopes are per resource anyway, and scopes can actually differ per resource. Consensus: No need to add a new "type" field for scope description documents.
