### ISSUE TITLE
Reconsider whether ticket should be on all redirect-back AS responses

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#298]
In Cigdem's pre-WG draft edit pass, she noted that it seemed odd to have the AS issue a ticket even for cases when the requesting party's interaction with it resulted obvious "no" results (this is in Core rev 20 [Sec 3.6.4](https://docs.kantarainitiative.org/uma/wg/uma-core-2.0-20.html#redirect-back)). I wrote back:

"Re always issuing tickets from redirect flows: I guess we could return no ticket but still redirect the RqP back to the client, and that would save a chatty round of interaction with the client because not_authorized means a definitive no. Technically, request_submitted could be the same; the client would be just marking time waiting to "poll" the resource again. We're being inconsistent in returning tickets for these if these two errors have the same meaning across the redirect and token endpoint contexts."

Should we reconsider?

**Comment by ciseng** [comment]
Yes, my question is:
By issuing a ticket for “not authorised” and “request submitted”, are we saying that the behaviour we want from the client that it directly approaches AS to try again?
These two cases, though, are different than “claims submitted” or “need_info” cases. In those cases,  the client is an ongoing authorisation process and need to talk to AS again as a next step almost immediately. 
While in “not authorised” and “request submitted” the authorisation evaluation ended, and possibly the RO needs to change something for the client to get access. I somewhat assumed time-to-live for tickets is short. Therefore, I expect any such policy change would take longer than ticket time-to-live, and hence, when the client approaches to AS, it will most likely get a ticket expired error.  It will have to approach RS anyway, in this case.

**Comment by jricher** [comment]
The RS has no way to tie in multiple requests from the client to each other, at least not prior to token issuance. Let's talk this through: if the client makes a request at the RS and gets a ticket, then presents that ticket and is told "request submitted". So at this point, what can the client do to get a token? It *has* to talk to the AS again. The only way for it to do that is with a (newly rotated) ticket. If the client goes back to the RS to get a new ticket, that ticket submitted to the AS will start a whole new transaction. What if my policy as the RO says "ask me every time"? This is a reasonable policy that we ought to be supporting. If we don't hand back a ticket with the "request submitted" response, then our client has no chance to *ever* be authorized.

Timeout shouldn't be an issue, as the authorization server gets to decide how long a ticket is good for. It would be trivial for an AS to decide that a ticket issued during "request submitted" lasts longer -- perhaps indefinitely until the RO can be reached.

**Comment by ciseng** [comment]
OK, I see your point - it may save some round trips, if AS returns the ticket. “Ask me every time” is also an interesting policy to support - which means ticket lifetimes should be tuned to that RO interaction time.

Though,  I think I am still missing why the client would have no chance to be authorised, if AS does not return a ticket with “request submitted” or the ticket, no matter how well configured it is, it expires.

After the “request submitted”, the client can go and try to the same action (to access a resource) at the RS. And yes, this creates a new ticket. The RS will ask for the necessary resources and scopes, and the ticket will contain the information about that. The client will approach AS with the new ticket, and if RO by that time changed anything, the client may get authorised and be granted a token. 
Am I missing something?

**Comment by jricher** [comment]
It's not about saving round trips, it's about connecting context. What you're missing is that the new ticket is effectively creating a new access request. I think your mental model of client use might be limited -- are you inadvertently assuming a single RqP per client? You can't assume that the same client is acting in the same context for the same user every time. In your scenario above, when the client submits another request to the RS (without authentication or identification, remember), the RS simply goes and fetches a new ticket. This is completely unrelated to the previously submitted authorization request. The RO might have authorized the first request by now -- but that doesn't matter. This isn't the first request, this is a brand new transaction with different context. In this world, if the RO says "ask me every time", then the first time the client presents a ticket, the AS is going to prompt the RO. If the client goes and gets a new ticket and presents that to the AS, then the AS is going to prompt the RO -- again. If the client has to go back to the RS and get a new ticket every time, it never has a chance of getting an access token, and all of this stems from a perfectly reasonable and defensible access policy: prompt the RO for each token request. If instead we return a ticket, we're giving the client a bound handle to continue the transaction at a future date.

On another note, I'm not entirely convinced by the "not approved" response, since the client could always present a different set of claims to potentially gain access. Maybe it's a good thing to have a definitive short circuit, but it seems conjectural to me.

**Comment by ciseng** [comment]
OK got it.  The problem was I did not think about this “ask me every time” RO through.

I took “request submitted” as a prompt for RO to do sth about its policies (which it may choose not to do anything about). Hence,   making “request submitted” and “not authorised” equivalent - so that, all subsequent requests may continue as if the previous authorisation attempt did not happen - directly with RS. 

But indeed, I am excluding here other cases like “ask me every time”, which requires context from previous attempts, and hence, a ticket.

**Comment by xmlgrrl** [comment]
Regarding "On another note, I'm not entirely convinced by the "not approved" response, since the client could always present a different set of claims to potentially gain access. Maybe it's a good thing to have a definitive short circuit, but it seems conjectural to me." It's a fair point. I don't believe our implemented access control system has a definitive "not authorized" distinction vs. "it happens not to qualify for the operative conditions right now", and other than having zero policy conditions (in a default-deny system etc. etc.) to compare against, I'm not sure how one would know just how _definitive_ the situation is.

**Comment by xmlgrrl** [comment]
This argument could apply to both the redirect back and the token endpoint levels, btw.

**Comment by xmlgrrl** [comment]
See the extensive discussion and recommendations in [UMA telecon 2017-04-13](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-04-13).

**Comment by xmlgrrl** [comment]
Actually, we already had most of the `error` machinery in there already, copied (by value) from OAuth. So implementing this means, essentially, deleting the authorization_state piece and removing the by-value stuff to replace it with a reference. Neat.

**Comment by xmlgrrl** [comment]
Per [UMA telecon 2017-04-20](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-04-20): "The redirect-back paths look much cleaner now."
