### ISSUE TITLE
Behaviour for invalid/expired claim_token

### ISSUE THREAD

**Issue by mrpotes** [KantaraInitiative/wg-uma#344]
If the client pushes invalid/expired claim_token, how should the AS respond - `need_info`? Should the spec define that behaviour?

**Comment by ciseng** [comment]
This would be need_info. AS could not use what was provided by the client, and lists them under required_claims again. I think we should define any behaviour in the spec that raises a question and cannot be answered immediately.

**Comment by xmlgrrl** [comment]
I'm inclined to agree on both points.

- If the authorization assessment has policies that can't be met by the claim token provided, the AS can always return `need_info` (with hints, at its option).
- Since this is a condition that calls for a response and the spec didn't say what to do and the question came up, we should fill in the spec gap.

**Comment by xmlgrrl** [comment]
Per UMA telecon [2017-08-08](https://groups.google.com/forum/#!topic/kantara-initiative-uma-wg/YLS0wIDqRz0), `need_info` is correct and we need to explain this condition for the error.
