### ISSUE TITLE
JWT/JWS profile to let host inspect the requester's permission token locally

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#51]

**Comment by nynymike** [comment]
Thread on the mailing list regarding this issue.

-------- Original Message --------
Subject: Re: [WG-UMA] Use signed JWT as RPT?
Date: 2015-10-01 12:08
From: Eve Maler <eve@xmlgrrl.com>
To: Michael Schwartz <mike@gluu.org>
Cc: "wg-uma@kantarainitiative.org UMA" <wg-uma@kantarainitiative.org>, John Bradley <ve7jtb@ve7jtb.com>

Indeed, John remembers correctly. We only defined a remote introspection flow early on so that the end-to-end UMA flow would be complete in the face of other pieces not being finished yet. There’s even an open issue on this:

https://github.com/KantaraInitiative/wg-uma/issues/51

We’ve just been waiting for someone to want it badly enough to write a profile for us to consider. A locally inspectable token would be attractive for some IoT use cases (though maybe a JWT wouldn’t be the best format for those — there are other candidates).

There are the usual tradeoffs: entitlement freshness vs. ability for the RS to be disconnected at run time (with attendant performance benefits throughout the ecosystem).

If you do this and want us to consider standardizing it, by all means submit it!

	Eve

> On 1 Oct 2015, at 8:44 AM, John Bradley <ve7jtb@ve7jtb.com> wrote:
> 
> I think I proposed that as a posable optimization a long time ago.
> 
> I think at the time JWT was a ways from being finished and people didn’t want to take a dependency on it.
> 
> The flow was left so it could be a future option.  
> 
> I don’t think that there is a security issue, but it is probably two or more years since I thought about it.
> 
> Perhaps George or someone else remembers more about the discussion at the time.
> 
> John B.
> 
>> On Oct 1, 2015, at 10:11 AM, Mike Schwartz <mike@gluu.org> wrote:
>> 
>> UMA-tarians,
>> 
>> One of Gluu's customers has proposed using a JWT as the RPT token signed by the AS to avoid the call to the introspection API (for better performance). It didn't seem like a horrible idea, or anything that would break the security. Any thoughts? Am I wrong--is there some inherent security advantage to calling the introspection API?
>> 
>> - Mike
>> 
>> 
>> -------------------------------------
>> Michael Schwartz
>> Gluu
>> Founder / CEO
>> _______________________________________________
>> WG-UMA mailing list
>> WG-UMA@kantarainitiative.org
>> http://kantarainitiative.org/mailman/listinfo/wg-uma
> 
> _______________________________________________
> WG-UMA mailing list
> WG-UMA@kantarainitiative.org
> http://kantarainitiative.org/mailman/listinfo/wg-uma


Eve Maler | cell +1 425.345.6756 | Skype: xmlgrrl | Twitter: @xmlgrrl | Calendar: xmlgrrl@gmail.com

-- 
-------------------------------------
Michael Schwartz
Gluu

**Comment by xmlgrrl** [comment]
In UMA telecon 2016-02-04, we had a back-channel discussion on this topic as follows:

Mike Schwartz@All: I don't think self-contained tokens is limited to IOT...
 Mike Schwartz@All: And also, I'm not sure its possilble...
 Justin Richer@All: Self contained tokens are in no way limited to IoT and that's not hte only issue of IoT. And how is it not possible? People have been doing it for many, many years.
 George Fletcher@All: agreed that self-contained tokens are limited to IoT. I also think that while we should use JWT for the token syntax there are some real issues to solve here. 
Mike Schwartz@All: of course self contained tokens are possible, but the way we defined the RPT flow 
Mike Schwartz@All: the RPT gets issued, and its empty 
Mike Schwartz@All: and then permissions get added.
 Mike Schwartz@All: So its not that RPT can't be self-contained, but it can't be used as an access token 
Mike Schwartz@All: because the access token value would change 
Justin Richer@All: That's not how we issue RPTs. We don't issue RPTs until there are permissions to it. If we add permissions we'd issue a new RPT which is valid. 
George Fletcher@All: Yes, or become a "super" token which has it's own security issues.
 Justin Richer@All: Right, super tokens are a big problem in wider cases.

**Comment by xmlgrrl** [comment]
Starting in UMA 2.0 Core rev 08, we still have a custom token introspection object (based on/inspired by 7662, which is itself JWT-based/inspired) because of the necessity of tying scopes to specific resources and the value of tying permission parameters to same, but the spec now acknowledges that local validation of a self-contained token (and caching of validation results) is also fine:

https://docs.kantarainitiative.org/uma/ed/uma-core-2.0-08.html#check-rpt-status
